name: Daily Financials Update Workflow

on:
  schedule:
    # UTC 15:10 → KST 다음날 00:10
    - cron: '10 15 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted  # Windows X64 self-hosted 러너

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data collector (재무제표 수집)
        shell: powershell
        continue-on-error: true
        env:
          DART_API_KEY:   ${{ secrets.DART_API_KEY }}
          DATABASE_URL:   ${{ secrets.DATABASE_URL }}
        run: |
          # 콘솔 인코딩을 UTF-8로 설정 (한글 깨짐 방지)
          chcp.com 65001
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

          # 에러 무시
          $ErrorActionPreference = 'Continue'

          # 파이썬 스크립트 직접 실행 (출력이 콘솔에 바로 표시됨)
          python main.py

      - name: Send notification email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          from:     ${{ secrets.GMAIL_USER }}
          to:       hmroh7363@gmail.com
          subject: >
            ${{ job.status == 'failure' && '❌ 재무정보 업데이트 실패'
               || '✅ 재무정보 업데이트 완료' }}
          body: >
            ${{ job.status == 'failure'
                && '예기치 못한 오류로 재무정보 수집이 실패했습니다.'
                || '정상적으로 재무정보 수집 및 DB 업로드가 완료되었습니다.' }}
